chore(examples): introducing a socket.io service example
winglang/examples pull request #25
Opened 2023-10-23 14:49 UTC by fl0wo

A simple example of a Service used as a WebSocket server, and a mini front-end to show its synchronization of a multiplayer game.

Ideally, I'd like to maintain it by introducing more services like Redis.
Also as soon as [#1306](https://github.com/winglang/wing/issues/1306) is resolved I'd try to do a test deployment on AWS seeing it running on ECS.

2023-10-25 07:23 UTC, skorfmann commented
Cool stuff! 

By default the CI assumes that `wing test --debug main.w` will have a test executed to tell if the example is working properly. Can you think of a test we could add here?

To disable AWS tests we can just add an empty `skip.ci.aws` file

2023-10-25 07:27 UTC, skorfmann requested changes

2023-10-25 07:27 UTC, skorfmann commented on examples/multiplayer-videogame/package.json
> +    "http": "^0.0.1-security",
why these packages ?

https://www.npmjs.com/package/http
https://www.npmjs.com/package/fs

I think that can be dropped.

2023-10-25 07:27 UTC, skorfmann commented on examples/multiplayer-videogame/README.md
> +- A [cloud.Service](https://www.winglang.io/docs/standard-library/cloud/secret) as a websocket broadcasting server
```suggestion
- A [cloud.Service](https://www.winglang.io/docs/standard-library/cloud/service) as a websocket broadcasting server
```

2023-10-26 22:04 UTC, fl0wo commented
Introduced 5 tests that check whether service execution and counter work well together.

I'm fairly new to open-source contributions, so I hope I didn't screw up the commits 😅

2023-11-03 12:25 UTC, skorfmann commented
Looks good, thanks! Gonna merge and fix potential ugprading issues locally.

2023-11-03 12:25 UTC, merged